# Generated by Django 3.1 on 2021-07-27 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drf_hooks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(db_index=True, max_length=64, verbose_name='Event')),
                ('target', models.URLField(max_length=255, verbose_name='Target URL')),
                ('headers', models.JSONField(default=drf_hooks.models.get_default_headers)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'swappable': 'HOOK_CUSTOM_MODEL',
            },
        ),
    ]
