language: python

arch:
  - amd64
  - ppc64le

python:
  - "2.7"
  - "3.4"
  - "3.6"
  - "3.8"

env:
  - DJANGO_VERSION="1.5"
  - DJANGO_VERSION="1.6"
  - DJANGO_VERSION="1.7"
  - DJANGO_VERSION="1.8"
  - DJANGO_VERSION="1.9"
  - DJANGO_VERSION="1.10"
  - DJANGO_VERSION="1.11"
  - DJANGO_VERSION="2.0"

install:
  - pip install -r devrequirements_${DJANGO_VERSION}.txt

#script: python runtests.py

matrix:
  exclude:
    - python: "3.6"
      env: DJANGO_VERSION="1.5"
    - python: "3.6"
      env: DJANGO_VERSION="1.6"
    - python: "3.6"
      env: DJANGO_VERSION="1.7"
    - python: "2.7"
      env: DJANGO_VERSION="2.0"
    - python: "3.8"
      env: DJANGO_VERSION="1.5"
    - python: "3.8"
      env: DJANGO_VERSION="1.6"
    - python: "3.8"
      env: DJANGO_VERSION="1.7"
    - python: "3.8"
      env: DJANGO_VERSION="1.8"
    - python: "3.8"
      env: DJANGO_VERSION="1.9"
    - python: "3.8"
      env: DJANGO_VERSION="1.10"
      

before_deploy:
  - pip install wheel
  - python setup.py sdist bdist_wheel

deploy:
  provider: pypi
  user: bryanhelmig
  password:
    secure: amY+WgU7S4RD/8S4rDz6/Gso1bucyqWWdCfG5RXHxD1mBcOIBjfiVmDkbiOxODany3KS5Hmo3mvXjOlpgmhuxw2iWdG1o059pMh8PH7I2WwHTliUSGwIshFIUmAivrh1mq9qUsHfsGpPow3AaxFB7G/FnrAQjedTTGYfN5ZnI/k=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: zapier/django-rest-hooks
